apiVersion: v1
kind: Service
metadata:
  name: demoflutterservice
  labels:
    app: demoflutterservice
spec:
  type: NodePort
  selector:
    app: demoflutter
  ports:
  - protocol: TCP
    port: 80
    name: http
    nodePort: 30226
      
      